# Generated by Django 4.0.4 on 2022-07-18 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_create_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 17, 13, 18, 922019)),
        ),
        migrations.AlterField(
            model_name='story',
            name='create_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 17, 13, 18, 922019)),
        ),
    ]
