# Generated by Django 4.0.4 on 2022-08-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0002_alter_notification_user_friendrequest_friendlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_active',
        ),
    ]
