# Generated by Django 4.0.4 on 2022-08-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0005_alter_chat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.TextField(default=' '),
        ),
    ]
