# Generated by Django 4.0.4 on 2022-08-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0007_alter_chat_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['create_on']},
        ),
    ]
