# Generated by Django 4.0.4 on 2022-08-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0008_alter_chat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-create_on']},
        ),
    ]
