# Generated by Django 4.1.1 on 2022-10-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0010_notification_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['create_on']},
        ),
    ]
