# Generated by Django 4.1.1 on 2022-10-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0011_alter_chat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
